# Optional: for local development orchestration
version: '3.8'
services:
  # Example service stub
  data-service:
    build: ./data-service
    container_name: cb-trade-data-service
    environment:
      - ENV=dev
    volumes:
      - ./data-service:/app
    ports:
      - "8000:8000"
