name: cb-trade
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip     
  - pandas
  - numpy
  - pydantic
  - pydantic-settings
  - azure-storage-blob
  - fastapi
  - uvicorn
  - websockets
  - pytest
  - pytest-asyncio
  - pytest-mock
  - pytest-dotenv
  - pytest-timeout
  - aiofiles
  - python-dotenv
  - pip:
    - ccxt  
