[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "data-service"
version = "0.1.0"
description = "Cyberbuild Trade Data Service"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["src"]
