name: Development CI & PR to Master

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the development branch
  push:
    branches:
      - development
  # Triggers the workflow on pull request events targeting the development branch
  pull_request:
    branches:
      - development

# Set default permissions for the GITHUB_TOKEN
# These permissions are necessary for the actions used in this workflow.
permissions:
  contents: write # Needed for peter-evans/create-pull-request to push a branch and create a PR
  packages: write # Needed to publish packages to GitHub Packages
  pull-requests: write # Needed to create pull requests

jobs:
  build-test-publish-and-pr:
    name: Build, Test, Publish & Create PR
    runs-on: ubuntu-latest # Specifies the type of runner the job will run on
    env: # Set environment variables for all steps in this job
      PYTHON DONTWRITEBYTECODE: '1' # Prevents Python from writing .pyc files

    steps:
      # 1. Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetches all history for all branches and tags.
          fetch-depth: 0

      # 2. Set up Conda environment
      # Ensure your environment.yml has 'name: cb-trade' and 'python=3.9'.
      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: cb-trade # Explicitly set to match environment.yml name
          environment-file: environment.yml # Path to your conda environment file
          python-version: '3.9' # Align with python=3.9 in environment.yml
          auto-activate-base: false # We want to activate the environment from the file

      # 3. Install build tools (if not already in environment.yml)
      # Best practice: include pip, build, pytest, wheel in environment.yml dependencies.
      - name: Install build and test tools (if needed)
        shell: bash -l # Ensures conda environment is activated for this step
        run: |
          echo "Ensuring build tools are present. Best practice: include them in environment.yml."
          # If 'pip', 'build', 'pytest', 'wheel' are in environment.yml, this step might be mainly for confirmation.
          # Example: conda install --name cb-trade --yes pip build pytest wheel
          # This command assumes the environment name is 'cb-trade'.

      # 4. (Optional but Recommended) Lint and Format Check
      # Example using Flake8 and Black. Adapt to your project's tools.
      # Ensure these are run within the conda environment.
      - name: Lint and Format Check
        shell: bash -l # Ensures conda environment is activated
        run: |
          # Ensure linters are installed in the conda env (e.g., via environment.yml)
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          black --check .

      # 5. Run tests
      # Assumes tests are run with pytest, using the conda environment's Python.
      - name: Run tests with Pytest
        shell: bash -l # Ensures conda environment is activated
        run: pytest

      # 6. Build package
      # This step uses the 'build' package, which requires a pyproject.toml.
      # It should use the Python from the activated conda environment.
      - name: Build package
        shell: bash -l # Ensures conda environment is activated
        run: python -m build

      # 7. Publish to GitHub Packages (only on direct push to development)
      - name: Publish package to GitHub Packages
        if: github.event_name == 'push' && github.ref == 'refs/heads/development'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.GITHUB_TOKEN }}
          repository_url: https://pypi.pkg.github.com/YOUR_USERNAME_OR_ORG/ # IMPORTANT: Replace with your GitHub username or organization

      # 8. Create Pull Request from development to master (only on direct push to development)
      - name: Create Pull Request to master
        if: github.event_name == 'push' && github.ref == 'refs/heads/development'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-PR: Merge development into master after successful CI"
          branch: auto-pr/development-to-master
          base: master
          head: development
          title: 'Auto-PR: Merge `development` into `master`'
          body: |
            Automated Pull Request
            - This PR was automatically created after a successful build, test, and package publish on the `development` branch.
            - Please review the changes before merging.

            Triggered by commit: ${{ github.sha }}
          labels: automated pr, development-merge
          # assignees: your-github-username
          # reviewers: your-github-username,another-reviewer
          # draft: false
